### ISSUE TITLE
ADD l10n_it_fatturapa_export_zip

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1051]
-  [x] v8: https://github.com/OCA/l10n-italy/pull/948
 - [x] v10: https://github.com/OCA/l10n-italy/pull/1030
 - [ ] v11:
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1065

**Comment by eLBati** [comment]
@OCA/local-italy-developers fatto merge per v10 e creata https://github.com/OCA/l10n-italy/pull/1065 per v12

**Comment by GSLabIt** [comment]
@eLBati hai idea se esiste già qualcosa di simile per l'importazione?

**Comment by eLBati** [comment]
@GSLabIt non che io sappia

**Comment by primes2h** [comment]
Merge effettuato per le PR delle principali versioni supportate. Chiudo.
