### ISSUE TITLE
[l10n_it_fatturapa] Add support to multiple invoice preview formats

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1057]
improve the e-invoice preview format by supporting multiple formats accessible by a dedicated selection in the fatturapa company options.

It also add the AssoSoftware preview format which is FAR better and readable compared to the one provided by ADE!

 - [x] v8: #1124 
 - [x] v10: https://github.com/OCA/l10n-italy/pull/1036
 - [x] v11: https://github.com/OCA/l10n-italy/pull/1171
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1066

**Comment by eLBati** [comment]
@OCA/local-italy-developers

**Comment by robyf70** [comment]
@eLBati la v11 è su #1171

**Comment by primes2h** [comment]
Andrebbe messa la spunta sulla v8, è stato fatto il merge.

**Comment by tafaRU** [comment]
Grazie @primes2h, fatto.

**Comment by primes2h** [comment]
Chiudo perché completata per tutte le versioni.
