### ISSUE TITLE
[IMP][l10n_it_fatturapa_in] Format Italian VAT ID to always have 11 chars

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1067]
- [x] v8: #1094 
 - [x] v10: https://github.com/OCA/l10n-italy/pull/984
 - [ ] v11: https://github.com/OCA/l10n-italy/pull/1106
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1112 #2000

**Comment by sergiocorato** [comment]
aggiornato con #2000 in caso ci siano caratteri extra
