### ISSUE TITLE
Campi DDT traducibili

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1071]
- [x] v8: https://github.com/OCA/l10n-italy/pull/217
 - [x] v10: https://github.com/OCA/l10n-italy/pull/580
 - [ ] v11: https://github.com/OCA/l10n-italy/pull/1522
 - [ ] v12: https://github.com/OCA/l10n-italy/pull/1523

**Comment by OpenCode** [comment]
11.0 -> #1522

**Comment by OpenCode** [comment]
12.0 -> #1523
