### ISSUE TITLE
Gestione ritenuta e Enasarco nelle fatture elettroniche emesse

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#1077]
- [x] v8: https://github.com/OCA/l10n-italy/pull/865
 - [x] v10: https://github.com/OCA/l10n-italy/pull/875
 - [ ] v11:
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1488

**Comment by primes2h** [comment]
Andrebbe messa la spunta sulla v12, è stato fatto il merge.

**Comment by tafaRU** [comment]
Grazie @primes2h, fatto.

**Comment by primes2h** [comment]
Merge effettuato per le PR delle principali versioni supportate. Chiudo.
