### ISSUE TITLE
Corretta ricerca del partner per codice fiscale - partita IVA e del commercial partner

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#1084]
- [x] v. 8.0 - https://github.com/OCA/l10n-italy/pull/894
- [x] v. 10.0 - https://github.com/OCA/l10n-italy/pull/843 [non conforme con la v. 12.0 e v. 8.0]
- [ ] v. 11.0 - 
- [x] v. 12.0 - https://github.com/OCA/l10n-italy/pull/846

**Comment by eLBati** [comment]
@sergiocorato per la 8 hai preso la versione della 12, giusto?

**Comment by sergiocorato** [comment]
> @sergiocorato per la 8 hai preso la versione della 12, giusto?

@eLBati si

**Comment by primes2h** [comment]
Andrebbe messa la spunta sulla v10, è stato fatto il merge della relativa PR.

**Comment by OpenCode** [comment]
> Andrebbe messa la spunta sulla v10, è stato fatto il merge della relativa PR.

Fatto

**Comment by eLBati** [comment]
Qualcuno farà per la 11 o chiudiamo?

**Comment by primes2h** [comment]
> Qualcuno farà per la 11 o chiudiamo?

@eLBati https://github.com/OCA/l10n-italy/issues/1452#issuecomment-576605967

**Comment by primes2h** [comment]
Merge effettuato per le PR delle principali versioni supportate. Chiudo.
