### ISSUE TITLE
[FIX] l10n_it_fatturapa_pec: correctly parse P7M files

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1189]
Versioni coinvolte:

 - [ ] v8: https://github.com/OCA/l10n-italy/pull/1188
 - [x] v10: https://github.com/OCA/l10n-italy/pull/1190
 - [ ] v11:
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1191

Descrizione del problema o della funzionalità:
Quando vengono caricate le fatture ricevute a sistema, quelle firmate digitalmente vengono scartate.

Comportamento desiderato:
Le fatture ricevute vengono memorizzate e in mail.message e viene creato un oggetto in fatturapa.attachment.in relativo alla nuova fattura
