### ISSUE TITLE
l10n_it_account: Constrain upon accounts and account groups + account_balance_sign for account.account.type

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1277]
Versioni coinvolte:

 - [ ] 8.0
 - [ ] 10.0: https://github.com/OCA/l10n-italy/pull/1286
 - [x] 11.0: https://github.com/OCA/l10n-italy/pull/1272
 - [x] 12.0: https://github.com/OCA/l10n-italy/pull/1278

Aggiunta constrain che impedisce ad un gruppo di conti di avere differenti tipologie di conto.
Viene lanciato errore se l'utente prova ad associare un conto di tipo X ad un gruppo composto da conti di tipo Y. Nessun gruppo di conti può avere conti di tipi diversi (se impostati).

Inoltre viene aggiunto il campo "Balance sign" su `account.account.type`, valorizzato, da usare poi nelle stampe di bilancio

**Comment by primes2h** [comment]
Andrebbe messa la spunta sulla v11 e sulla v12, è stato fatto il merge delle relative PR.
