### ISSUE TITLE
Bug calcolo ritenute V11

### ISSUE THREAD

**Issue by elvise** [OCA/l10n-italy#1299]
Versioni coinvolte:

 - [ ] 8.0 ?
 - [x] 10.0 https://github.com/OCA/l10n-italy/pull/1348
 - [x] 11.0: https://github.com/OCA/l10n-italy/pull/1346
 - [x] 12.0 https://github.com/OCA/l10n-italy/pull/1350

Passi per riprodurre: 
Creo una nuova fattura cliente > inserisco il cliente > inserisco un prodotto > inserisco il prezzo a 100$ > inserisco iva 22% > inserisco ritenuta al 4% > modifico il prezzo da 100$ a 90$ il valore della ritenuta è sbagliato

Comportamento osservato:
All'interno della riga fattura, ogni volta che modifichi il valore prezzo o quello della ritenuta, viene sommato il valore di tutte le ritenute all'interno della tabella "Ritenuta" nel tab "Altre Informazioni"

Comportamento atteso:

Video/Screenshot (opzionale):
http://recordit.co/MFGed16X7i

**Comment by GSLabIt** [comment]
https://github.com/OCA/l10n-italy/pull/1346

**Comment by eLBati** [comment]
@sergiocorato per la 8 sai se serve? O chiudo?

**Comment by primes2h** [comment]
Merge effettuato per le PR delle principali versioni supportate. Chiudo.
