### ISSUE TITLE
Stampa registro IVA: opzione per ordinamento

### ISSUE THREAD

**Issue by alessandrocamilli** [OCA/l10n-italy#1414]
Aggiunta l'opzione per ordinare i movimenti sul registro.
Si può scegliere tra:
- Data/numero
- Sezionale/data/numero
 - [x] 8.0: #573 (risolta per termine supporto)
 - [x] 14.0: inclusa in https://github.com/OCA/l10n-italy/pull/4376 
 - [x] 16.0: https://github.com/OCA/l10n-italy/pull/3971

**Comment by eLBati** [comment]
riapro con https://github.com/OCA/l10n-italy/pull/3971
