### ISSUE TITLE
Always e-mail contacts about pec errors

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#1430]
Le mail riguardanti FE che non riescono ad essere importate vengono lette da fetchmail ma non processate (non viene creato l'allegato in Odoo).

Sarebbe bene avvertire l'utente quando questo succede.

**Versioni coinvolte**
 - [x] v8: https://github.com/OCA/l10n-italy/pull/1530
 - [x] v10: https://github.com/OCA/l10n-italy/pull/1431
 - [ ] v11: https://github.com/OCA/l10n-italy/pull/1531
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1533

**Comment by eLBati** [comment]
Il porting alla 12 dipende da https://github.com/OCA/l10n-italy/pull/1394 (per `l10n_it_fatturapa_pec/models/company.py`)

**Comment by OpenCode** [comment]
@SimoRubi Devi fare il porting anche della 11.0?

**Comment by SimoRubi** [comment]
> @SimoRubi Devi fare il porting anche della 11.0?

non è in previsione

**Comment by OpenCode** [comment]
Lo faccio io allora :)

**Comment by eLBati** [comment]
@SimoRubi @OpenCode per v12: https://github.com/OCA/l10n-italy/pull/1533

**Comment by robyf70** [comment]
@SimoRubi Mi chiedevo se dovremmo gestire anche la ``raise`` su https://github.com/OCA/l10n-italy/blob/10.0/l10n_it_fatturapa_pec/models/mail_thread.py#L70-L80 e consentire di andare avanti invece che interrompere la lettura delle email

**Comment by SimoRubi** [comment]
@robyf70 l'eccezione è scatenata in `message_route` che è chiamato da `message_process`: https://github.com/odoo/odoo/blob/52526920085e94727ddc12d188af826ede7fd6d9/addons/mail/models/mail_thread.py#L1285

quindi credo che venga già gestita da https://github.com/OCA/l10n-italy/blob/3a62c70437baa896b16fea7b230d8c04069d7f4e/l10n_it_fatturapa_pec/models/fetchmail.py#L70-L71

Subito dopo averla gestita, si passa alla mail successiva con `continue` quindi la lettura delle mail non dovrebbe essere interrotta.

**Comment by robyf70** [comment]
@SimoRubi Quello che rilevo è alla riga 67 dove ``att`` è ``False``

https://github.com/OCA/l10n-italy/blob/3a62c70437baa896b16fea7b230d8c04069d7f4e/l10n_it_fatturapa_pec/models/mail_thread.py#L62-L83

si tratta di un messaggio di consegna che arriva con un nome che non viene trovato da 

https://github.com/OCA/l10n-italy/blob/3a62c70437baa896b16fea7b230d8c04069d7f4e/l10n_it_fatturapa_pec/models/mail_thread.py#L142-L156

alle righe 146-147. Ma non viene trovato perchè nella tabella ``fatturapa.attachment.out`` abbiamo:
```
ProductionDB=# select id, create_date, name, datas_fname from ir_attachment where name like 'IT03552000923_00005%' and res_model='fatturapa.attachment.out';
  id   |        create_date         |              name              |          datas_fname           
-------+----------------------------+--------------------------------+--------------------------------
  6111 | 2019-04-17 07:53:12.348735 | IT03552000923_00005_NS_001.xml | IT03552000923_00005_NS_001.xml
  6530 | 2019-04-26 07:47:52.631289 | IT03552000923_00005_NS_001.xml | IT03552000923_00005_NS_001.xml
 30999 | 2019-11-20 13:42:40.947565 | IT03552000923_00005_NS_001.xml | IT03552000923_00005_NS_001.xml
(3 rows)
```
Ed ovviamente non si capisce cosa stà succedendo.

**Comment by SimoRubi** [comment]
@robyf70 non mi sembra il problema per cui ho creato questo issue, ma sicuramente è un problema!
Se il problema che dici è slegato da questa issue, suggerisco di aprirne una dedicata.

Parlando invece del problema, ci dovrebbe essere il vincolo SQL https://github.com/OCA/l10n-italy/blob/3a62c70437baa896b16fea7b230d8c04069d7f4e/l10n_it_fatturapa_out/models/attachment.py#L31-L34
sulla tabella it_attachment_out che vieta di avere diversi allegati con lo stesso nome, sembra che il vincolo non sia attivo sul tuo `ProductionDB`, quindi direi che come prima cosa potresti correggere quello.
Per farlo devi eliminare gli allegati duplicati e aggiornare il modulo, credo che questo attiverà il vincolo, altrimenti ci dovrebbe essere un warning nei log che ti spiega cosa fare.

Una volta fatto questo, credo che https://github.com/OCA/l10n-italy/blob/3a62c70437baa896b16fea7b230d8c04069d7f4e/l10n_it_fatturapa_pec/models/mail_thread.py#L142-L156
riuscirà a trovare l'allegato giusto.

**Comment by robyf70** [comment]
@SimoRubi Si hai ragione, il problema è slegato da questo ticket
