### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/l10n-italy#148]
:warning: Attenzione: considerato che la frequenza annuale dei rilasci di Odoo implica un notevole sforzo tecnico di porting dei moduli di localizzazione, il PSC OCA Italia ha deciso di concentrare gli sforzi sulle ultime 2 versioni pari.

Le PR sulle versioni con minore priorità potranno essere fatte ma riceveranno meno amore.

# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] l10n_it_base_crm
- [ ] l10n_it_sale
- [ ] l10n_it_account
- [ ] l10n_it_ateco
- [ ] l10n_it_bill_of_entry
- [ ] l10n_it_partially_deductible_vat
- [ ] l10n_it_abicab
- [ ] l10n_it_corrispettivi
- [ ] account_invoice_entry_date
- [ ] l10n_it_ipa
- [ ] l10n_it_split_payment
- [ ] l10n_it_DDT_webkit
- [ ] account_central_journal
- [ ] l10n_it_fiscalcode
- [ ] account_fiscal_year_closing
- [ ] l10n_it_vat_registries
- [ ] l10n_it_ricevute_bancarie
- [ ] l10n_it_rea
- [ ] l10n_it_withholding_tax
- [ ] l10n_it_pec
- [ ] l10n_it_fatturapa
- [x] l10n_it_base_location_geonames_import
- [ ] account_vat_period_end_statement
- [ ] l10n_it_prima_nota_cassa
- [ ] l10n_it_CEE_balance_generic
- [ ] account_invoice_sequential_dates
- [ ] l10n_it_fatturapa_out
- [ ] l10n_it_base
