### ISSUE TITLE
Print withholding tax in pdf invoice

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1504]
Versioni coinvolte:

 - [ ] 10.0
 - [x] 11.0 https://github.com/OCA/l10n-italy/pull/1543
 - [x] 12.0 https://github.com/OCA/l10n-italy/pull/2193
 - [x] 14.0 https://github.com/OCA/l10n-italy/pull/2364

Add withholding tax in invoice PDF. Ability to hide/show it from invoice "other info" -> show in pdf

**Comment by SimoRubi** [comment]
v14: https://github.com/OCA/l10n-italy/pull/2364
