### ISSUE TITLE
l10n_it_fatturapa_out: decode single function and more info in usererror

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1506]
Versioni coinvolte:
 
 - [ ] 8.0 https://github.com/OCA/l10n-italy/pull/1544
 - [ ] 10.0
 - [ ] 11.0: https://github.com/OCA/l10n-italy/pull/1570
 - [x] 12.0: https://github.com/OCA/l10n-italy/pull/1515

esportazione di fatture con nome del cliente o via o altro con caratteri non latini

Correlata a https://github.com/OCA/l10n-italy/issues/1507

**Comment by zeroincombenze** [comment]
Scusa eLBati, il problema non è nella fattura elettronica che utilizza UTF-8 ma nei dichiariativi fiscali (esterometro) che utilizzavano latin-1.
Per quanto mi ricordo anche lo spesometro light è passato a UTF-8
Forse sarebbe opportuno effettuare un piccolo controllo prima di inziare un lavoro pazzesco inutile

**Comment by eLBati** [comment]
Nessun lavoro pazzesco è previsto.
Questa issue riguarda `l10n_it_fatturapa_out` e la soluzione è contenuta nella PR https://github.com/OCA/l10n-italy/pull/1505 , al momento solo per la 8

Per l'esterometro bisogna aprire un'altra issue e le relative PR. Il mio suggerimento è di seguire, per `l10n_it_invoices_data_communication`, lo stesso approccio seguito da `l10n_it_fatturapa_out`

**Comment by zeroincombenze** [comment]
Ah scusa, non avevo capito.
Credevo che fosse un issue dalla discussione in chat!
:-(

**Comment by sergiocorato** [comment]
aggiornamento: sulla PR ho splittato la funzione per i campi che necessitano di ascii e quelli di latin1 e inserito anche il controllo del numero massimo di caratteri previsto dal formato (magari si potrà estendere ad altri campi)
