### ISSUE TITLE
l10n_it_invoices_data_communication: XML con encoding="latin1" invece di encoding="utf8"

### ISSUE THREAD

**Issue by vincenzoterzulli** [OCA/l10n-italy#1507]
Versioni coinvolte:
- [x] 8.0   - https://github.com/OCA/l10n-italy/pull/1544
- [ ] 10.0 - Non ancora accertata
 - [x] 11.0: https://github.com/OCA/l10n-italy/pull/1570
- [x] 12.0 - https://github.com/OCA/l10n-italy/pull/1515

**Descrizione del problema:**
* L'Agenzia delle Entrate (ADE) accetta il file della comunicazione se esso presenta la proprietà _encoding='latin1'_ per l'elemento _xml_, in prima riga:
`<?xml version='1.0' encoding='latin1'?>`
In caso contrario rigetta il file con errore *00200* - "File non conforme al formato"
* il problema si presenta quando sopratutto in presenza di anagrafiche fornitore con denominazione o indirizzi compilati mediante copia/incolla da pagine web.

**Approfondimenti:**
* Elenco dei controlli effettuati sul file DATI FATTURA https://www.agenziaentrate.gov.it/portale/documents/20143/284857/Elenco%2Bdei%2Bcontrolli%2Beffettuati%2Bsul%2Bfile%2Bdati%2Bfattura.pdf/718d7f2b-af0a-0d85-2ea5-0d1f7194cee2
* esempi di conversioni da terminale Python, in verde la soluzione con risultato atteso:
![image](https://user-images.githubusercontent.com/16492632/67510897-20f58780-f696-11e9-929a-6bb01f48b74b.png)
* Esempi e soluzioni di problemi simili: 
https://stackoverflow.com/questions/1207457/convert-a-unicode-string-to-a-string-in-python-containing-extra-symbols

**Passi per riprodurre:**
* caricare fatture di acquisto da fornitori esteri, con denominazioni o indirizzi con simboli non latini, ad esempio (ö, ä, ß)
* da _Contabilità >> Registrazione Sezionali >> Comunicazione dati fatture_ generare una nuova comunicazione (Esterometro) contenente le fatture sopra create
* esportare il file XML da _Altro >> Esportazione file comunicazione dati fatture_
* aprire il file XML con un editor di testo e osservare il valore per la proprietà _encoding_ a linea 1

**Comportamento osservato:**
- Il file XML generato è scritto correttamente con codifica _UTF-8_, 
![image](https://user-images.githubusercontent.com/16492632/67509167-af680a00-f692-11e9-840c-15a95fbb2601.png)

- la prima riga del file dichiara  codifica _encoding='utf8'_ per gli elementi interni e il file contiene stringhe con simboli presenti in UTF-8, ma non presenti in LATIN1 (ISO-8859-1)
![image](https://user-images.githubusercontent.com/16492632/67509291-f8b85980-f692-11e9-8f50-88ccea1b0090.png)
* il file viene rigettato dall'ADE:
![image](https://user-images.githubusercontent.com/16492632/67507991-5c8d5300-f690-11e9-8ee5-fa8fb79c9232.png)

**Comportamento atteso:**
- Il file XML generato è scritto correttamente con codifica _UTF-8_, 
![image](https://user-images.githubusercontent.com/16492632/67509172-b1ca6400-f692-11e9-8755-3ddd3bcffbed.png)
- la prima riga del file dichiara codifica _encoding='latin1'_ per gli elementi interni e il file contiene stringhe con solo simboli latini e il carattere '?' al posto dei simboli non latini
![image](https://user-images.githubusercontent.com/16492632/67508677-be01f180-f691-11e9-83d1-c7a27abb73f3.png)
- il file viene accettato dall'ADE

**Comment by eLBati** [comment]
Per v12: https://github.com/OCA/l10n-italy/pull/1515

**Comment by eLBati** [comment]
Nel porting a 12 è emerso un dubbio che vale anche per la 8
https://github.com/OCA/l10n-italy/pull/1515#pullrequestreview-310337505

@Byloth @labaggio @vincenzoterzulli che ne pensate?
