### ISSUE TITLE
Nuove specifiche tecniche fattura elettronica [1.6]

### ISSUE THREAD

**Issue by marco-marchiori** [OCA/l10n-italy#1670]
### Analisi

Qui di seguito il link alle [nuove specifiche tecniche](https://www.agenziaentrate.gov.it/portale/web/guest/provvedimento-del-28-febbraio-2020) emanate dal Direttore dell'Agenzia delle entrate lo scorso 28 febbraio.

Nelle intenzioni, vorrebbero consentire 
- il superamento della "comunicazione polivalente" (c.d. esterometro) per le operazioni con l'estero
- la liquidazione precompilata
- una piu' agevole rappresentazione della previdenza

Ad una veloce lettura, i principali cambiamenti riguardano:
- header, controllo che per alcuni tipi documento il codice IdPaese sia diverso da IT
- dati ritenuta, (si ampliano le casse rappresentabili)
- nuovi tipi documento TD16..TD27
- Tipi ritenuta codificati per casse previdenziali
- "Natura" operazione analiticamente descritta e ripresa nei dati riepilogo
- un nuovo metodo di pagamento
- codici errore.

[Fattura elettronica, le nuove specifiche tecniche: tutti i codici](https://www.agendadigitale.eu/documenti/fatturazione-elettronica/fattura-elettronica-le-nuove-specifiche-tecniche-tutti-i-codici/)

### Sviluppo

Operativamente, per la generazione dei nuovi bindings: https://github.com/OCA/l10n-italy/blob/12.0/l10n_it_fatturapa/bindings/README.md (il `sed` sarà probabilmente da adattare alla nuova versione)

Il primo obiettivo è avere l'insieme delle modifiche pronte per la 12, per poi portarle alle altre versioni.
Usiamo https://github.com/OCA/l10n-italy/tree/12.0-l10n_it_fatturapa-1.6 come branch di deploy su cui far confluire i vari contributi.

L'analisi dei singoli punti e il lavoro fatto si trova in https://docs.google.com/document/d/1MQCkcMU278OC0Yzsup2UrXLuqh8FV-iZLilgSwq__ZQ

**Nota**
Per rendere il successivo lavoro di backporting più modulare, e come tale più facile da distribuire, si è deciso di splittare la issue corrente in sotto issue.
Ciascuna delle quali conterrà il link alla PR verso il branch target e non verso il branch principale OCA. Tutte le PR verso il branch principale OCA **dovranno** essere chiuse per evitare che vengano "mergiate" accidentalmente.

### TODO list

- [x] emissione fatture con ritenute: nuovi codici dati ritenuta: https://github.com/OCA/l10n-italy/issues/1789
- [x] modifica del type di Importo in ScontoMaggiorazioneType: https://github.com/OCA/l10n-italy/issues/1797
- [x] modifica della enumeration di CausalePagamentoType: https://github.com/OCA/l10n-italy/issues/1785
- [x] modifica della enumeration di Tipo Documento: https://github.com/OCA/l10n-italy/issues/1799
- [x] modifica della enumeration di NaturaType: https://github.com/OCA/l10n-italy/issues/1800
- [x] nuova modalità di pagamanto: https://github.com/OCA/l10n-italy/issues/1787
- [x] opzionalità per l’elemento ImportoBollo non più obbligatorio: https://github.com/OCA/l10n-italy/issues/1802
- [x] codice valore senza encoding: https://github.com/OCA/l10n-italy/issues/1790
- [x] ricezione fatture con ritenute: #1877 
- [x] pulizia commit
- [x] verificare su SDI tutti gli XML modificati (vedi ad esempio https://github.com/OCA/l10n-italy/commit/e5d135cc4a817bacca272f0c283dc9880a7238e8)
- [x] preview e-fattura: verificare che le preview funzionino ancora sia con la vecchia versione dell'XML che con quella nuova
- [x] gestire i nuovi tipi di reverse charge nel modulo `l10n_it_fatturapa_in_rc` (https://github.com/OCA/l10n-italy/pull/1906) https://github.com/OCA/l10n-italy/blob/26ec8b20f82d0a4ef0e35ede83b0fe04d62eb48b/l10n_it_fatturapa_in_rc/wizard/wizard_import_fatturapa.py#L10  e `l10n_it_invoices_data_communication` (https://github.com/OCA/l10n-italy/pull/1907) https://github.com/OCA/l10n-italy/blob/26ec8b20f82d0a4ef0e35ede83b0fe04d62eb48b/l10n_it_invoices_data_communication/models/account_invoice.py#L40

Creare branch dedicati su cui far confluire le PR direttamente:
- [x] 8.0: https://github.com/OCA/l10n-italy/pull/1912
- [x] 10.0: #1986
- [ ] 11.0: WIP @OpenCode 
- [x] 12.0: https://github.com/OCA/l10n-italy/pull/1873

**Comment by OpenCode** [comment]
Volevo solo segnalare che manca la versione 10 in quelle elencate e che comunque, come da segnalazione, daremo ufficialmente supporto alle ultime versioni tenendo conto di quelle pari. La 13 perciò è fuori e le versioni vintage anche.

**Comment by marco-marchiori** [comment]
Grazie per la correzione

**Comment by OpenCode** [comment]
Mi sono permesso di aggiornare la descrizione con la situazione delle versioni. Man mano che verranno aperte le PR e Mergiate si aggiornerà anche la stessa.

**Comment by sergiocorato** [comment]
Ho aggiornato il link, presumo l'abbiano spostato

**Comment by eLBati** [comment]
Operativamente, per la generazione dei nuovi bindings: https://github.com/OCA/l10n-italy/blob/12.0/l10n_it_fatturapa/bindings/README.md (il `sed` sarà probabilmente da adattare alla nuova versione)

**Comment by eLBati** [comment]
Per quanto riguarda le date:
https://www.agendadigitale.eu/documenti/fatturazione-elettronica/tracciati-fattura-elettronica-tutte-le-novita-dellagenzia-delle-entrate/

**Comment by sergiocorato** [comment]
Direi che operativamente si potrebbero creare delle issue figlie di questa per tracciare le singole modifiche da fare, tipo:
- [] codici tipo documento;
- [] codici natura;
- [] ecc. ecc.

**Comment by SimoRubi** [comment]
Aggiornamento binding: https://github.com/OCA/l10n-italy/issues/1783

**Comment by SimoRubi** [comment]
Nuova modalità di pagamento: https://github.com/OCA/l10n-italy/issues/1787

**Comment by CiroBoxHub** [comment]
Nuovi codici dati ritenuta #1789

**Comment by SimoRubi** [comment]
Nuovo tipo tipo String35LatinExtType (solo per CodiceValore) https://github.com/OCA/l10n-italy/issues/1790

**Comment by eLBati** [comment]
https://github.com/OCA/l10n-italy/pull/1784#issuecomment-644035243

**Comment by eLBati** [comment]
https://t.me/Odoo_ITA_Sviluppo/13926

**Comment by tafaRU** [comment]
> > Dovreste aggiornare la Issue #1670 raccogliendo tutte le informazioni relative ai lavori in corso. Inoltre suggerisco di chiudere tutte le Issue aperte relative alle singole funzionalità e di raccogliere tutto sulla 1670, nell'ottica appunto di avere un'unica PR con tutti i commit

@eLBati fatto!

**Comment by robyf70** [comment]
@eLBati Stò iniziando le PR per la v10

**Comment by robyf70** [comment]
@eLBati L'ultima PR include tutto per il supporto alle specifiche v1.6

**Comment by jado95** [comment]
Ho un'errore se provo ad aggiornare il modulo fatturapa_in su un db dove avevo già i moduli fatturapa installati.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gianmarco/odoo12/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/gianmarco/odoo12/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/gianmarco/odoo12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/gianmarco/odoo12/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/home/gianmarco/odoo12/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/gianmarco/odoo12/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/gianmarco/odoo12/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/gianmarco/odoo12/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/gianmarco/odoo12/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/gianmarco/odoo12/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/gianmarco/odoo12/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/gianmarco/odoo12/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/gianmarco/odoo12/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-67>", line 2, in button_immediate_upgrade
  File "/home/gianmarco/odoo12/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/gianmarco/odoo12/odoo/odoo/addons/base/models/ir_module.py", line 622, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/home/gianmarco/odoo12/odoo/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/gianmarco/odoo12/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/gianmarco/odoo12/odoo/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/gianmarco/odoo12/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/gianmarco/odoo12/odoo/odoo/modules/loading.py", line 195, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/home/gianmarco/odoo12/odoo/odoo/modules/registry.py", line 307, in init_models
    models[0].recompute()
  File "/home/gianmarco/odoo12/odoo/odoo/models.py", line 5287, in recompute
    vals = {n: rec[n] for n in ns}
  File "/home/gianmarco/odoo12/odoo/odoo/models.py", line 5287, in <dictcomp>
    vals = {n: rec[n] for n in ns}
  File "/home/gianmarco/odoo12/odoo/odoo/models.py", line 5134, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/gianmarco/odoo12/odoo/odoo/fields.py", line 1009, in __get__
    self.determine_value(record)
  File "/home/gianmarco/odoo12/odoo/odoo/fields.py", line 1098, in determine_value
    self.compute_value(recs)
  File "/home/gianmarco/odoo12/odoo/odoo/fields.py", line 1076, in compute_value
    self._compute_value(records)
  File "/home/gianmarco/odoo12/odoo/odoo/fields.py", line 1067, in _compute_value
    getattr(records, self.compute)()
  File "/home/gianmarco/odoo12/fatturapa-1.6/l10n-italy/l10n_it_fatturapa_in/models/attachment.py", line 82, in _compute_xml_data
    fatt = wiz_obj.get_invoice_obj(att)
  File "/home/gianmarco/odoo12/fatturapa-1.6/l10n-italy/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py", line 1431, in get_invoice_obj
    xml_string = fatturapa_attachment.get_xml_string()
  File "/home/gianmarco/odoo12/fatturapa-1.6/l10n-italy/l10n_it_fatturapa_in/models/attachment.py", line 74, in get_xml_string
    return self.ir_attachment_id.get_xml_string()
  File "/home/gianmarco/odoo12/fatturapa-1.6/l10n-italy/l10n_it_fatturapa/models/ir_attachment.py", line 106, in get_xml_string
    return self.cleanup_xml(data)
  File "/home/gianmarco/odoo12/fatturapa-1.6/l10n-italy/l10n_it_fatturapa/models/ir_attachment.py", line 68, in cleanup_xml
    xml_string = self.remove_xades_sign(xml_string)
  File "/home/gianmarco/odoo12/fatturapa-1.6/l10n-italy/l10n_it_fatturapa/models/ir_attachment.py", line 50, in remove_xades_sign
    root = ET.XML(xml, parser=recovering_parser)
  File "src/lxml/lxml.etree.pyx", line 3192, in lxml.etree.XML (src/lxml/lxml.etree.c:78763)
  File "src/lxml/parser.pxi", line 1848, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:118341)
  File "src/lxml/parser.pxi", line 1736, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:117021)
  File "src/lxml/parser.pxi", line 1102, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:111265)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105109)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106817)
  File "src/lxml/parser.pxi", line 646, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105963)
  File "<string>", line 0
lxml.etree.XMLSyntaxError: <no detail available>

**Comment by sergiocorato** [comment]
A seguito ultimi sviluppi, gli errori sul travis da verificare sono:
- https://travis-ci.org/github/OCA/l10n-italy/jobs/727643404#L2809 (su l10n_it_fatturapa_out_wt)
- https://travis-ci.org/github/OCA/l10n-italy/jobs/727643404#L2903 (su un file e-invoice probabilmente non più accettabile)
per chi ha disponibilità e interesse

**Comment by OpenCode** [comment]
Ho aggiornato la descrizione aggiungendo la presa in carico del backport della PR per la 12.0 alla 11.0

**Comment by stevech091** [comment]
@robyf70 vorrei testare la versione 1.6 per la V10 dove la posso trovare?

**Comment by luky0071** [comment]
Ciao a tutti, sicuramente sto sbagliando qualcosa, ma nell'aggiornare i moduli per la versione 1.6 della FE Odoo 12 ricevo una serie di errori; nello specifico allego l'errore provando ad aggiornare il modulo fatturapa
Sapresti darmi qualche dritta?
Ho provato anche su Odoo 10, ma anche li, va in errore

Errore:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/models.py", line 1117, in _validate_fields
    check(self)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 351, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 1099, in postprocess_and_fields
    fields_def = self.postprocess(model, node, view_id, False, fields)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 924, in postprocess
    fields.update(self.postprocess(model, f, view_id, in_tree_view, model_fields))
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 924, in postprocess
    fields.update(self.postprocess(model, f, view_id, in_tree_view, model_fields))
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 924, in postprocess
    fields.update(self.postprocess(model, f, view_id, in_tree_view, model_fields))
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 924, in postprocess
    fields.update(self.postprocess(model, f, view_id, in_tree_view, model_fields))
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 884, in postprocess
    ).postprocess_and_fields(field.comodel_name, f, view_id)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 1111, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 548, in raise_view_error
    raise ValueError(message)
ValueError: Il campo `electronic_invoice_use_this_address` non esiste

Contesto errore:
Vista `res.partner.form.e.invoice`
[view_id: 1369, xml_id: n/d, model: res.partner, parent_id: 113]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/odoo/odoo-server/odoo/models.py", line 3879, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/odoo/odoo-server/addons/website/models/ir_ui_view.py", line 129, in _load_records_create
    records = super(View, self)._load_records_create(values)
  File "/odoo/odoo-server/odoo/models.py", line 3793, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo-server/odoo/models.py", line 3610, in create
    fields[0].determine_inverse(batch_recs)
  File "/odoo/odoo-server/odoo/fields.py", line 1141, in determine_inverse
    getattr(records, self.inverse)()
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/odoo/odoo-server/addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/odoo/odoo-server/odoo/models.py", line 3335, in write
    self._write(store_vals)
  File "/odoo/odoo-server/odoo/models.py", line 3471, in _write
    self._validate_fields(vals)
  File "/odoo/odoo-server/odoo/models.py", line 1121, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Errore nella validazione del vincolo\n\nIl campo `electronic_invoice_use_this_address` non esiste\n\nContesto errore:\nVista `res.partner.form.e.invoice`\n[view_id: 1369, xml_id: n/d, model: res.partner, parent_id: 113]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-67>", line 2, in button_immediate_upgrade
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 622, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/odoo/odoo-server/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 802, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 865, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 764, in parse
    exc_info[2]
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/odoo/odoo-server/odoo/models.py", line 3879, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/odoo/odoo-server/addons/website/models/ir_ui_view.py", line 129, in _load_records_create
    records = super(View, self)._load_records_create(values)
  File "/odoo/odoo-server/odoo/models.py", line 3793, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo-server/odoo/models.py", line 3610, in create
    fields[0].determine_inverse(batch_recs)
  File "/odoo/odoo-server/odoo/fields.py", line 1141, in determine_inverse
    getattr(records, self.inverse)()
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/odoo/odoo-server/addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/odoo/odoo-server/odoo/models.py", line 3335, in write
    self._write(store_vals)
  File "/odoo/odoo-server/odoo/models.py", line 3471, in _write
    self._validate_fields(vals)
  File "/odoo/odoo-server/odoo/models.py", line 1121, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Errore nella validazione del vincolo

Il campo `electronic_invoice_use_this_address` non esiste

Contesto errore:
Vista `res.partner.form.e.invoice`
[view_id: 1369, xml_id: n/d, model: res.partner, parent_id: 113]
None" while parsing /odoo/custom/addons/l10n_it_fatturapa/views/partner_view.xml:40, near
<record id="view_partner_form_e_inv" model="ir.ui.view">
        <field name="name">res.partner.form.e.invoice</field>
        <field name="model">res.partner</field>
        <field name="inherit_id" ref="base.view_partner_form"/>
        <field name="arch" type="xml">
            <xpath expr="//div[@name='div_address']/../../.." position="after">
                <group string="E-invoicing" name="e_invoice_info" groups="account.group_account_invoice" attrs="{'invisible': ['|', ('type', '=', 'contact'), '|', ('parent.electronic_invoice_subjected', '=', False), ('parent.electronic_invoice_obliged_subject', '=', False)]}">
                    <group>
                        <field name="electronic_invoice_use_this_address"/>
                    </group>
                    <group attrs="{'invisible': [('electronic_invoice_use_this_address','=', False)]}">
                        <field name="ipa_code" placeholder="IPA123" attrs="{'invisible': [('parent.is_pa','=', False)]}"/>
                        <field name="codice_destinatario" attrs="{'invisible': [('parent.is_pa', '=', True)]}"/>
                        <field name="pec_destinatario" attrs="{'invisible': ['|',('parent.is_pa', '=', True), ('codice_destinatario', '!=', '0000000')]}"/>
                        <field name="eori_code"/>
                    </group>
                </group>
            </xpath>
        </field>
    </record>

**Comment by PatosMarco** [comment]
La versione 1.6 per Odoo 10 è ancora in alto mare? Perché non vedo request per buona parte della TODO List. O mi sto sbagliando?

**Comment by tafaRU** [comment]
@PatosMarco al momento esiste https://github.com/OCA/l10n-italy/pull/1899 Se hai modo di contribuire potremmo accelerare il suo processo di Merge!

**Comment by EveilidiaDevelopment** [comment]
Salve a tutti e grazie. Fatemi sapere che manca cosi' do una mano anche io
