### ISSUE TITLE
[l10n_it_account_stamp] Inserimento automatico bollo non funziona in particolare condizioni

### ISSUE THREAD

**Issue by marcelofrare** [OCA/l10n-italy#1686]
**Versioni coinvolte:** 

- [ ] 10.0 da verificare, dipende da #1058.
- [x] 11.0 commit: 0aab4a583dac0b16599e2ae109be7f5450ed4874 di #1610 (dipende da https://github.com/OCA/l10n-italy/commit/2e6bac6cc5bbe6d9ee1cc461383926859d1d0ad3)
- [x] ~12.0~ non si presenta (https://github.com/OCA/l10n-italy/pull/1728)

### **TEST CASE n.1**

**Passi per riprodurre:**

1. Creare una fattura con due righe:
una con un prodotto di valore zero
una con prodotto di valore €100 e iva al 22%

2. cancellare da ogni riga l'aliquota assegnata (22%)
3. rimettere l'imposta associata al bollo (esente) prima alla riga a valore ZERO e poi alla riga di valore €100 

**Comportamento osservato:**
Il bollo virtuale non viene proposto automaticamente

**Comportamento atteso:**
Il bollo dovrebbe essere proposto visto che le condizioni finali sono conformi alla specifica 

Video/Screenshot (opzionale):
![immagine](https://user-images.githubusercontent.com/25057933/76150294-0eaa4200-60a9-11ea-9062-f4b9ee7c8301.png)

### **TEST CASE n.2**

**Passi per riprodurre:**

1. inserisco una riga con un valore inferiore al limite previsto per il bollo e salvo
2. entro in modifica della riga aumentando la qta/prezzo affinchè il subtotale superi il limite x il bollo

**Comportamento osservato:**
Il bollo virtuale non viene proposto automaticamente

**Comportamento atteso:**
Il bollo dovrebbe essere proposto visto che le condizioni finali sono conformi alla specifica 

![immagine](https://user-images.githubusercontent.com/25057933/82129026-2811ed80-97c0-11ea-8f38-d93a3cf65e70.png)

**Comment by mymage** [comment]
@marcelofrare Il problema si risolve con l'osservazione che ho indicato qui: https://github.com/OCA/l10n-italy/pull/1610#issuecomment-596142367
Appena risolvo l'inghippo lo segnalo.

**Comment by marcelofrare** [comment]
Verificando i due TEST CASE su https://runbot.odoo.com/runbot, mi sono accorto che il comportamento tra la ver.11.0 e la ver.12.0 non è uguale:
sulla ver.11.0 il totale della fattura si aggiorna quando mi sposto di riga
sulla ver.12.0 il totale della fattura si aggiorna dopo aver cliccato su SALVA

**Comment by eLBati** [comment]
@marcelofrare non ricordavo questa issue, però recentemente abbiamo fatto merge di https://github.com/OCA/l10n-italy/pull/1728 che potrebbe aver risolto questo problema

**Comment by marcelofrare** [comment]
@eLBati: ho ricontrollato adesso, ti confermo che sulla v.12 non si presenta l'anomalia che invece è presenta sulla v.11.
