### ISSUE TITLE
Estensione l10n_it_ricevute_bancarie

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#1734]
Versioni coinvolte: 
- [ ] 12.0

Aggiunta di varie funzionalità utili per l'uso e alcuni fix:
- [x] fix in caso il nome del movimento sia '/' e quindi non rilevante #1733 
- [ ] data accettazione impostabile e campi date spostati in posizione sempre visibile #1735 
- [x] dati più dettagliati nella riba emessa #1743 
- [ ] in caso di raggruppamento riba, possibilità di emettere riba raggruppandone negative (da n.c.) con positive, controllando che il totale resti positivo (es. una riba negativa da n.c. e una riba positiva da fattura con la stessa scadenza viene emessa una sola riba per la differenza)  #1740 
- [x] ripristino vista elenco linee riba emesse #1746 
- [ ] modulo extra per aggiungere una modalità diversa di gestione dell'incasso finale con accreditamento parziale delle distinte in varie date #1747 
- [x] modifica ordinamento distinte ri.ba. per data di creazione discendente #1749 
- [x] rimozione file inutilizzati #1757 
~- [ ] possibilità di impostare una banca specifica nel partner per le riba, senza necessità di iban #1736 #1741~
- [ ] creazione di una riba a mano
