### ISSUE TITLE
[fatturazione elettronica 1.6] Binding per fatturazione elettronica 1.6

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#1783]
**Versioni coinvolte**

 - [ ] v8: https://github.com/OCA/l10n-italy/pull/1795
 - [ ] v10: https://github.com/OCA/l10n-italy/pull/1860
 - [ ] v12: https://github.com/OCA/l10n-italy/pull/1784

**Comment by vincenzoterzulli** [comment]
Con le specifiche tecniche v1.6 la fattura elettronica subisce delle variazioni.
Nel dettaglio questa ISSUE traccia gli aggiornarmenti dei binding e dei fogli di stile per operare correttamente con il nuovo schema XSD di FatturaPA versione 1.2.1

**Comment by eLBati** [comment]
https://github.com/OCA/l10n-italy/issues/1670#issuecomment-644082541

**Comment by robyf70** [comment]
PR per la v10 è su #1860
