### ISSUE TITLE
Tipo documento fiscale: migliorie per i nuovi tipi documento

### ISSUE THREAD

**Issue by alessandrocamilli** [OCA/l10n-italy#2072]
Versioni coinvolte:

- [ ] 10.0
- [x] 11.0 https://github.com/OCA/l10n-italy/pull/2074
- [x] 12.0 https://github.com/OCA/l10n-italy/pull/2075
- [x] 14.0 https://github.com/OCA/l10n-italy/pull/2541

Passi per riprodurre:
Vengono utilizzati 2 sezionali per le fatture di vendita.
Uno per quelle immediate e uno per quelle differite.
Ora per questi documenti esistono 2 tipo di documenti fiscali: TD01 e TD24.
Per questo si procede ad indicare nelle rispettive tipologie i relativi sezionali.
Quindi nel TD01 ci sarà il sezionale per le fatture immediate e nel TD24 quello per quelle differite.
Poi si procede a fare una nota di credito

Comportamento osservato:
Per entrambe le fatture il tipo di documento impostato è quello della fattura TD01 e TD24 e non il tipo documento per le note di credito. Occorre quindi manualmente andare a modificarlo. Se l'utente si dimentica si rischia di mandare all'SDI un documento errato.

Comportamento atteso:
La nota credito prenda il tipo documento previsto TD04

Video/Screenshot (opzionale):

**Comment by eLBati** [comment]
Chiudo.
Se qualcuno vuole farlo per la 10, riapriamo

**Comment by tafaRU** [comment]
riapro perchè ho incluso la `14.0 `

**Comment by eLBati** [comment]
Ma ` l10n_it_fiscal_document_type` non è presente su `14.0` quindi la modifica dovrebbe essere inclusa nella PR di porting

**Comment by scigghia** [comment]
preparo la PR per V14.0

**Comment by scigghia** [comment]
va aggiornata la issue dato che la PR per V14 è stata mergiata

**Comment by tafaRU** [comment]
> va aggiornata la issue dato che la PR per V14 è stata mergiata

ok, qual è la PR? Questa: https://github.com/OCA/l10n-italy/pull/2541?

**Comment by OpenCode** [comment]
> va aggiornata la issue dato che la PR per V14 è stata mergiata

Fatto
