### ISSUE TITLE
[12.0] Errore durante l'importazione fattura elettronica

### ISSUE THREAD

**Issue by Borruso** [OCA/l10n-italy#2093]
Buonasera,
per un cliente ci è arrivata una fattura elettronica con arrotondamento a -0.003.
Se questa fattura la importo con il minimo va in errore poiché cerca di prendere il max() delle righe in fattura, che al minimo non esistono, e invece che 0 va in errore per mancanza di argomento.
Ora bisogna impostare a 0 se le righe non ci sono o, dato che è al minimo, non aggiungere neanche la riga di arrotondamento??

Questo è il file XML:
[IT08940791216_00325.zip](https://github.com/OCA/l10n-italy/files/5920303/IT08940791216_00325.zip)

 - [x] 10.0 https://github.com/OCA/l10n-italy/pull/2183
 - [x] 12.0 https://github.com/OCA/l10n-italy/pull/2107
 - [x]  14.0 https://github.com/OCA/l10n-italy/blob/91eac51ddc9c3d93db94e4420899cd80c73083bc/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py#L1243

**Comment by SimoRubi** [comment]
Verificato in runbot v12, dopo aver impostato round up/down account.
Facendo importazione minima, l'errore è:
```
[...]
  File "/home/odoo/build/OCA/l10n-italy/setup/l10n_it_fatturapa_in/odoo/addons/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py", line 1488, in importFatturaPA
    fatt, fatturapa_attachment, fattura, partner_id)
  File "/home/odoo/build/OCA/l10n-italy/setup/l10n_it_fatturapa_in/odoo/addons/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py", line 1020, in invoiceCreate
    self.set_roundings(FatturaBody, invoice)
  File "/home/odoo/build/OCA/l10n-italy/setup/l10n_it_fatturapa_in/odoo/addons/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py", line 1133, in set_roundings
    line_sequence = max(invoice.invoice_line_ids.mapped('sequence'))
ValueError: max() arg is an empty sequence
```

**Comment by TheMule71** [comment]
Stesso problema pure io:
![image](https://user-images.githubusercontent.com/915043/107381012-b4063b00-6aee-11eb-9669-2b3c9f6dd06b.png)
![image](https://user-images.githubusercontent.com/915043/107381076-c7b1a180-6aee-11eb-9a19-6a3da6ba85c1.png)
[IT05979361218_016.zip](https://github.com/OCA/l10n-italy/files/5952114/IT05979361218_016.zip)

**Comment by TheMule71** [comment]
Giuseppe e Simone, se potete, testate la PR.

**Comment by eLBati** [comment]
In seguito alla chiusura della https://github.com/OCA/l10n-italy/pull/2107 , questa si può chiudere?

**Comment by TheMule71** [comment]
Chiudo perché nella 14.0 è risolto.
