### ISSUE TITLE
l10n_it_intrastat_statement: force round to 1 for additional_units field only if has a value

### ISSUE THREAD

**Issue by fredzamoabg** [OCA/l10n-italy#2249]
Versioni coinvolte:

- [x] [10.0] https://github.com/OCA/l10n-italy/pull/2232
- [x] [12.0]  https://github.com/OCA/l10n-italy/pull/2254
- [x] [14.0] https://github.com/OCA/l10n-italy/pull/2259

Comportamento osservato:
il ricalcolo della dichiarazione fa valorizzare un campo additional_units ad 1 anche se la nomenclatura non richiede una udm supplementare.

Comportamento atteso:
arrotondare ad 1 solo in caso il valore di additional_units sia compreso tra (0.0, 0.5)

**Comment by eLBati** [comment]
v12: https://github.com/OCA/l10n-italy/pull/2254
