### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/l10n-italy#254]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] ~~account_central_journal~~ --> l10n_it_central_journal
- [ ] ~~account_fiscal_year_closing~~ replaced by https://github.com/OCA/account-closing/tree/10.0/account_fiscal_year_closing
- [x] ~~account_invoice_entry_date~~ **deprecated** - @OpenCode
- [x] ~~account_invoice_sequential_dates~~ - @dcorio - deprecate in favour of account_invoice_constraint_chronology
- [x] account_vat_period_end_statement
- [ ] l10n_it_CEE_balance_generic
- [x] l10n_it_abicab - @dcorio - #262 
- [x] l10n_it_account - @eLBati https://github.com/OCA/l10n-italy/pull/295
- [x] l10n_it_ateco -  @CiroBoxHub
- [x] ~~l10n_it_base~~ **deprecated** - @OpenCode -  #273
- [ ] l10n_it_base_crm
- [x] l10n_it_base_location_geonames_import - @OpenCode - #260 
- [ ] l10n_it_bill_of_entry - @dbrus - https://github.com/OCA/l10n-italy/pull/381
- [ ] l10n_it_corrispettivi - @drdran 
- [x] l10n_it_fatturapa - @eLBati - #265 
- [x] l10n_it_fatturapa_out - @eLBati - #265 
- [ ] l10n_it_fatturapa_out_sale @sergiocorato  #1489
- [x] l10n_it_fiscalcode - @andrea4ever - #267 
- [x] l10n_it_ipa - @eLBati - #264 
- [ ] l10n_it_partially_deductible_vat
- [x] l10n_it_pec - @OpenCode - #268 
- [ ] l10n_it_prima_nota_cassa
- [x] l10n_it_rea - @andrea4ever - #261 
- [x] l10n_it_ricevute_bancarie - @scigghia - #271
- [x] l10n_it_split_payment - @eLBati - #288
- [x] l10n_it_vat_registries - @eLBati https://github.com/OCA/l10n-italy/pull/295
- [x] l10n_it_withholding_tax - @alessandrocamilli - #266 
- [x] l10n_it_ddt - @tafaRU - https://github.com/OCA/l10n-italy/pull/294

**Comment by eLBati** [comment]
@dcorio about ```account_invoice_sequential_dates``` I read
> moved to account-invoicing

Is there any PR yet?
I think we should port [account_invoice_constraint_chronology](https://github.com/OCA/account-financial-tools/tree/8.0/account_invoice_constraint_chronology) to 10

**Comment by marco-carboni** [comment]
Hello, since account_invoice_entry_date is marked as deprecated, is there any alternative to this module? Thanks

**Comment by eLBati** [comment]
@marco-carboni in odoo core, you can find the ```Accounting Date``` field in ```other info``` tab of supplier invoices

**Comment by marco-carboni** [comment]
Saw it already thanks

**Comment by drdran** [comment]
@eLBati I'm working in progress with the l10n_it_corrispettivi actually for the 10.0 release of odoo.
I'ts in pre-alpha, after that i need help to make tests.

**Comment by eLBati** [comment]
ok @drdran thanks

**Comment by sergiocorato** [comment]
- [ ] l10n_it_fatturapa_out_sale #1489

**Comment by sergiocorato** [comment]
chiudo per inattività
