### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/l10n-italy#2967]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

Extra undocumented steps (see commit descriptions):
- https://github.com/odoo/odoo/commit/26b2472f4977ccedbb0b5ed5f08be2c04313fd21 `user_type_id` -> `account_type` ~~`account.account.type`~~
- https://github.com/odoo/odoo/commit/d8d47f9ff8554f4b39487fd2f13c153c7d6f958d - refactoring of  `account.move` methods (`@onchange`)
- https://github.com/odoo/odoo/commit/23483865b1508346f5a5e178f4a436fe1a9d9f55 - some fields became HTML from Text
- https://github.com/odoo/odoo/commit/785d49f3f0a21720d8c929d597d4041918ab7f41 - (silently) changes sig of function `_get_reconciled_invoices_partials()`
- https://github.com/odoo/odoo/commit/1595c0ee27c7a261f8903dccb9dc550224c2aa05 - refactoring of `env`
- https://github.com/odoo/odoo/commit/3dad4b3cb1cb823ae6ccbf56b990012ceca61d99 - refactoring di `account.payment.term`
- odoo/odoo@b9194406ecc8cf99d9747c2164838f3e092e0ec4 - renaming of `env['account.fiscal.position'].get_fiscal_position()` to `_get_fiscal_position`
- every change made to dot-files in the repo root is lost during migration. Maybe we should discuss to put those changes all together in a single commit, right after repo creation, as the first merge.

The following cmdline command is usuful (addresses both 15.0 and 16.0):
```
egrep -r "t-raw|\"ir.model|SavepointCase|\.manage|name_search|groups_id|fields_get_keys|get_xml_id|flush\(|recompute\(|refresh\(|invalidate_cache\(|account.account.type|user_type_id" --include \*.py --include \*xml .
```

|name|internal_type|account_type|
| ------------- | ------------- |------------- |
|Receivable (Clienti)|receivable|asset_receivable|
|Bank and Cash|liquidity|asset_cash|
|Current Assets|other|asset_current|
|Non-current Assets|other|asset_non_current|
|Fixed Assets|other|asset_fixed|
|Expenses|other|expense|
|Depreciation|other|expense_depreciation|
|Cost of Revenue|other|expense_direct_cost|
|Off-Balance Sheet|other|off_balance|
|Payable|payable|liability_payable|
|Credit Card|liquidity|liability_credit_card|
|Prepayments|other|asset_prepayments|
|Current Liabilities|other|liability_current|
|Non-current Liabilities|other|liability_non_current|
|Equity|other|equity|
|Current Year Earnings|other|equity_unaffected|
|Income (Revenue)|other|income|
|Other Income|other|income_other|

# Modules to migrate
- [x] account_tax_balance - https://github.com/OCA/account-financial-reporting/pull/937
- [x] account_vat_period_end_statement - By @michelerusti - #3028
- [x] assets_management (**da rinominare in** _l10n_it_asset_management_) - ~~By @odooNextev  #3271~~ @SirAionTech #3776
- [x] currency_rate_update_boi - By @Borruso - #3643
- [ ] fiscal_epos_print - By @Borruso - #3060
- [x] l10n_it_abicab - ~~By @Borruso - #2977~~ @tafaRU https://github.com/OCA/l10n-italy/pull/3036
- [x] l10n_it_account - @TheMule71 #2990 
- [ ] l10n_it_account_balance_eu > renamed l10n_it_financial_statement_eu - By @TennyMkt - #3599
- [x] l10n_it_account_stamp - @jado95  https://github.com/OCA/l10n-italy/pull/3021
- [x] l10n_it_account_tax_kind - @TheMule71 #2993
- [x] l10n_it_appointment_code - @Borruso https://github.com/OCA/l10n-italy/pull/3001
- [ ] [l10n_it_asset_history_import]
- [x] l10n_it_ateco - ~~By @Borruso - #2978~~ @tafaRU - https://github.com/OCA/l10n-italy/pull/3035
- [x] l10n_it_central_journal_reportlab - By @Borruso - #3002
- [x] l10n_it_declaration_of_intent - ~~By @ArcadioPinto - #3026~~ @tafaRU  - https://github.com/OCA/l10n-italy/pull/3081
- [x] l10n_it_delivery_note - @Borruso - https://github.com/OCA/l10n-italy/pull/3020
- [x] l10n_it_delivery_note_base - @Borruso - https://github.com/OCA/l10n-italy/pull/3019
- [x] l10n_it_delivery_note_batch - By @OpenCode - #3636
- [ ] l10n_it_delivery_note_customer_code
- [ ] l10n_it_delivery_note_inter_company 
- [ ] l10n_it_delivery_note_inter_warehouse 
- [x] l10n_it_delivery_note_order_link - By @Borruso - #3022
- [x] l10n_it_fatturapa - @TheMule71 #2995
- [x] l10n_it_fatturapa_export_zip - By @Borruso - #3332
- [x] l10n_it_fatturapa_import_zip - By @SirAionTech - #3584
- [x] l10n_it_fatturapa_in  - @TheMule71 #3000
- [x] l10n_it_fatturapa_in_purchase - By @Borruso - #3333
- [x] l10n_it_fatturapa_in_rc - By @SirAionTech - #3612
- [x] l10n_it_fatturapa_out - @TheMule71 #2996
- [x] l10n_it_fatturapa_out_di - By @Borruso - #3178
- [x] l10n_it_fatturapa_out_oss - By @Borruso - #3818
- [x] l10n_it_fatturapa_out_rc - By @SirAionTech - #3571
- [x] l10n_it_fatturapa_out_sp - By @Borruso - #3392
- [x] l10n_it_fatturapa_out_stamp - By @Borruso - #3179
- [ ] l10n_it_fatturapa_out_triple_discount - By @SirAionTech - #3720
- [ ] l10n_it_fatturapa_out_welfare
- [x] l10n_it_fatturapa_out_wt - By @Borruso - #3181
- [x] l10n_it_fatturapa_pec - By @Borruso - #3190
- [x] l10n_it_fatturapa_sale - By @Borruso - #3077
- [ ] l10n_it_fatturapa_sdicoop
- [x] l10n_it_financial_statements_report - By @SirAionTech - #3619
- [x] l10n_it_fiscalcode - @TheMule71 #2994 
- [x] l10n_it_fiscal_document_type - @TheMule71 #2991
- [x] l10n_it_fiscal_payment_term - @TheMule71 #2992
- [x] l10n_it_fiscalcode_sale - By @odooNextev - #3567
- [x] l10n_it_intrastat - By @Borruso - #3069
- [x] l10n_it_intrastat_statement - By @Borruso - #3327
- [x] l10n_it_ipa - By @TheMule71 - #2987
- [ ] l10n_it_location_nuts - By @Vincenzo9191 - #3029
- [x] l10n_it_payment_reason  - @TheMule71 #2997
- [x] l10n_it_pec - By @tafaRU - #3015
- [ ] l10n_it_pos_fatturapa
- [ ] l10n_it_pos_fatturapa_send_directly
- [x] l10n_it_pos_fiscalcode - By @Borruso - #3079
- [x] l10n_it_reverse_charge - By @SirAionTech - #3566
- [x] l10n_it_ricevute_bancarie - By @SirAionTech - #3615
- [x] l10n_it_rea - By @TheMule71 - #2988
- [x] l10n_it_sdi_channel - By @Borruso - #3189
- [x] l10n_it_split_payment - By @Borruso - #3387
- [x] l10n_it_vat_payability - By @TheMule71 - #2989
- [x] l10n_it_vat_registries - By @SirAionTech - #3564
- [x] l10n_it_vat_registries_split_payment - By @Borruso - #3394
- [x] l10n_it_vat_statement_communication - By @TonyMasciI - #3137
- [x] l10n_it_vat_statement_split_payment - By @SirAionTech - #3638
- [x] l10n_it_website_portal_fatturapa - By @Borruso - #3406
- [ ] l10n_it_website_portal_fatturapa_sale
- [x] l10n_it_website_portal_fiscalcode - ~~By @AlessandroSkab - #3025~~ By @aleuffre - https://github.com/OCA/l10n-italy/pull/3338
- [x] l10n_it_website_portal_ipa - By @Borruso - #3027
- [ ] l10n_it_website_sale_fatturapa
- [ ] l10n_it_website_sale_fiscalcode
- [x] l10n_it_withholding_tax - By @TheMule71 - #2998
- [x] l10n_it_withholding_tax_payment - By @SirAionTech - #3637
- [x] l10n_it_withholding_tax_reason - By @TheMule71 - #2999

Elenco moduli su cui è auspicabile avere una revisione funzionale : https://github.com/OCA/l10n-italy/labels/needs%20functional%20review

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by Borruso** [comment]
migrando modulo l10n_it_appointment_code (#3001)

**Comment by jado95** [comment]
Inizio migrazione l10n_it_account_stamp

**Comment by michelerusti** [comment]
Inizio migrazione l10n_it_fiscalcode

**Comment by tafaRU** [comment]
Inizio a migrare `l10n_it_pec`

**Comment by Borruso** [comment]
Inizio migrazione `l10n_it_declaration_of_intent`

**Comment by Vincenzo9191** [comment]
Inizio migrazione l10n_it_location_nuts

**Comment by Borruso** [comment]
Inizio a migrare `l10n_it_delivery_note_base`

**Comment by Borruso** [comment]
Inizio a migrare `l10n_it_delivery_note`

**Comment by jado95** [comment]
l10n_it_account_stamp: #3021

**Comment by Borruso** [comment]
Inizio a migrare `l10n_it_delivery_note_customer_code`

**Comment by Borruso** [comment]
Inizio a migrare `l10n_it_website_portal_ipa`

**Comment by AlessandroSkab** [comment]
Inizio migrazione l10n_it_website_portal_fiscalcode

**Comment by michelerusti** [comment]
Inizio migrazione account_vat_period_end_statement

**Comment by jado95** [comment]
Inizio migrazione l10n_it_delivery_note_batch

**Comment by jado95** [comment]
l10n_it_delivery_note_batch: #3032

**Comment by Borruso** [comment]
Inizio a migrare `l10n_it_intrastat`

**Comment by Borruso** [comment]
Inizio a migrare l10n_it_fatturapa_sale (https://github.com/OCA/l10n-italy/pull/3077)

**Comment by Borruso** [comment]
Inizio a migrare `l10n_it_pos_fiscalcode` (#3079)

**Comment by TonyMasciI** [comment]
Inizio a migrare `l10n_it_reverse_charge` (https://github.com/OCA/l10n-italy/pull/3103)

**Comment by TonyMasciI** [comment]
Inizio a migrare `l10n_it_ricevute_bancarie` (https://github.com/OCA/l10n-italy/pull/3131)

**Comment by TonyMasciI** [comment]
Inizio a migrare `l10n_it_vat_statement_communication` (https://github.com/OCA/l10n-italy/pull/3135)

**Comment by tafaRU** [comment]
Per chi volesse prendere in carico le seguenti migrazione:

- l10n_it_fatturapa_out_di
- l10n_it_fatturapa_out_rc
- l10n_it_fatturapa_out_sp
- l10n_it_fatturapa_out_stamp
- l10n_it_fatturapa_out_wt

può partire da https://github.com/andreampiovesana/addons_it/tree/16.0

**Comment by Borruso** [comment]
Inizio a migrare `l10n_it_fatturapa_out_di` (#3178)

**Comment by Borruso** [comment]
Inizio a migrare `l10n_it_fatturapa_out_stamp` (https://github.com/OCA/l10n-italy/pull/3179)

**Comment by Borruso** [comment]
Inizio a migrare l10n_it_sdi_channel (#3189)

**Comment by Borruso** [comment]
Inizio a migrare l10n_it_fatturapa_pec (#3190)

**Comment by jado95** [comment]
l10n_it_fatturapa_out_rc: #3202

**Comment by Borruso** [comment]
`l10n_it_fatturapa_export_zip`: #3332

**Comment by Borruso** [comment]
`l10n_it_fatturapa_in_purchase` #3333

**Comment by odooNextev** [comment]
Si può aggiungere alla lista il modulo `l10n_it_fiscalcode_sale`?
Tra poco pubblichiamo la PR sia per la v14 che per la v16

**Comment by tafaRU** [comment]
> Si può aggiungere alla lista il modulo `l10n_it_fiscalcode_sale`?

@odooNextev lo facciamo non appena pubblichi le PR con l'aiuto di ocabot (nel caso della `16.0`)  :wink:

**Comment by maxgrassi** [comment]
Modulo: account_vat_period_end_statement
Testato su Odoo 16

Segnalo problema di visualizzazione nella scheda conti del modulo account_vat_period_end_statement di Odoo 16.

Testato su: https://runboat.odoo-community.org/webui/builds.html?repo=OCA/l10n-italy&target_branch=16.0

Riprodurre la problematica: Generare una liquidazione iva e spostarsi sulla scheda conti, compare una striscia bianca verticale in RIGHE CONTI DI CREDITO tra conto e imposta.

<img width="1241" alt="errore-di-visualizzazione" src="https://github.com/OCA/l10n-italy/assets/18476727/66c34345-40a2-43a0-8be9-b7a02f15e2e3">

**Comment by odooNextev** [comment]
prendo in carico l10n_it_fatturapa_in_rc

**Comment by Marcoapu** [comment]
inizio la migrazione di: l10n_it_delivery_note_customer_code

**Comment by Marcoapu** [comment]
inizio la migrazione del modulo l10n_it_delivery_note_order_link

**Comment by CiroBoxHub** [comment]
Il modulo l10n_it_fatturapa_out_dn è stato sostituito da qualche altro modulo? Non lo vedo in lista

**Comment by matteoopenf** [comment]
> l10n_it_fatturapa_out_dn

https://github.com/OCA/l10n-italy/pull/2202

**Comment by SirTakobi** [comment]
> Il modulo l10n_it_fatturapa_out_dn è stato sostituito da qualche altro modulo? Non lo vedo in lista

Non c'è nemmeno nella `14.0` ancora

**Comment by odooNextev** [comment]
> > > Si può aggiungere alla lista il modulo `l10n_it_fiscalcode_sale`?
> > 
> > 
> > @odooNextev lo facciamo non appena pubblichi le PR con l'aiuto di ocabot (nel caso della `16.0`) 😉
> 
> Ecco la PR per la v16: #3342

Potete sostituire la #3342 con la #3484?

P.S. ha tutti i test ok, mancano solo revisioni

**Comment by SirAionTech** [comment]
Inizio a migrare **l10n_it_financial_statements_report**

**Comment by SirAionTech** [comment]
Inizio a migrare **l10n_it_bill_of_entry**

**Comment by Borruso** [comment]
**currency_rate_update_boi**: #3643

**Comment by odooNextev** [comment]
`l10n_it_invoices_data_communication` non dovrebbe più servire se vengono inviate tutte le fatture comprese quelle estere

**Comment by sergiocorato** [comment]
> `l10n_it_invoices_data_communication` non dovrebbe più servire se vengono inviate tutte le fatture comprese quelle estere

Concordo, tra l'altro se qualcuno non le invia tramite SdI probabilmente non userebbe questo modulo ma le farebbe inviare dal commercialista.

**Comment by SirAionTech** [comment]
Grazie @odooNextev @sergiocorato, ho aggiornato la descrizione
