### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/l10n-italy#391]
:warning: Attenzione: considerato che la frequenza annuale dei rilasci di Odoo implica un notevole sforzo tecnico di porting dei moduli di localizzazione, il PSC OCA Italia ha deciso di concentrare gli sforzi sulle ultime 2 versioni pari.

Le PR sulle versioni con minore priorità potranno essere fatte ma riceveranno meno amore.

# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] account_central_journal
- [ ] account_fiscal_year_closing
- [ ] account_invoice_entry_date
- [ ] account_invoice_report_ddt_group
- [X] ~~account_invoice_sequential_dates~~ - @OpenCode - DEPRECATED after this:
- [ ] l10n_it_base_location_geonames_import - @dcorio 
- [ ] account_vat_period_end_statement - @jackjack82 - https://github.com/OCA/l10n-italy/pull/524
- [ ] l10n_it_CEE_balance_generic
- [x] l10n_it_abicab - @OpenCode - #426
- [x] l10n_it_account - @jackjack82 - https://github.com/OCA/l10n-italy/pull/522
- [ ] l10n_it_ateco
- [ ] l10n_it_base_crm
- [X] ~~l10n_it_base_location_geonames_import~~ - @OpenCode - DEPRECATED after this: https://github.com/OCA/partner-contact/pull/529
- [ ] l10n_it_bill_of_entry
- [x] l10n_it_codici_carica
- [x] l10n_it_corrispettivi
- [x] l10n_it_corrispettivi_sale - @SimoRubi - https://github.com/OCA/l10n-italy/pull/596
- [ ] l10n_it_ddt - @SilvioGregorini - https://github.com/OCA/l10n-italy/pull/538
- [x] l10n_it_esigibilita_iva
- [ ] l10n_it_fatturapa
- [ ] l10n_it_fatturapa_out
- [x] l10n_it_fiscalcode - @OpenCode - #425
- [ ] ~l10n_it_fiscalcode_invoice~ - deprecated, see https://github.com/OCA/l10n-italy/pull/623
- [ ] l10n_it_ipa
- [ ] l10n_it_partially_deductible_vat
- [x] l10n_it_pec - @OpenCode - #423
- [ ] l10n_it_prima_nota_cassa
- [x] l10n_it_rea - @primes2h - https://github.com/OCA/l10n-italy/pull/611
- [ ] l10n_it_reverse_charge - @jackjack82 - https://github.com/OCA/l10n-italy/pull/531
- [ ] l10n_it_ricevute_bancarie - @jackjack82 - https://github.com/OCA/l10n-italy/pull/526
- [x] l10n_it_split_payment - @ruben-tonetto  - https://github.com/OCA/l10n-italy/pull/652
- [ ] l10n_it_vat_registries - @eLBati - https://github.com/OCA/l10n-italy/pull/548
- [x] l10n_it_withholding_tax - By @alessandrocamilli - #523 
- [x] l10n_it_withholding_tax_payment - @alessandrocamilli - https://github.com/OCA/l10n-italy/pull/523
- [x] l10n_it_website_sale_corrispettivi - @SimoRubi - #608

**Comment by alessandrocamilli** [comment]
please update list with migration of 
l10n_it_withholding_tax and l10n_it_withholding_tax_payment
https://github.com/OCA/l10n-italy/pull/523

**Comment by SimoRubi** [comment]
Migrating l10n_it_ddt_delivery in https://github.com/OCA/l10n-italy/pull/587

**Comment by SimoRubi** [comment]
Superseding https://github.com/OCA/l10n-italy/pull/538 with https://github.com/OCA/l10n-italy/pull/588

**Comment by SimoRubi** [comment]
#585 merged

**Comment by SimoRubi** [comment]
Migrating l10n_it_corrispettivi_sale in #596

**Comment by SimoRubi** [comment]
Migrating l10n_it_website_sale_corrispettivi in https://github.com/OCA/l10n-italy/pull/608

**Comment by primes2h** [comment]
Migrating l10n_it_rea in #611

**Comment by ruben-tonetto** [comment]
Migrating 11.0-mig-l10n_it_split_payment, superseding #525 with #652
Please update list.

**Comment by sergiocorato** [comment]
chiudo per inattività
