### ISSUE TITLE
Fattura PA - vincolo data >= 1970-01-01 errore se nell'xml c'è il timezone --> pyxb 1.2.6

### ISSUE THREAD

**Issue by sherpya** [OCA/l10n-italy#879]
Secondo specifica la data deve essere nel formato 8601:2004, il vincolo inserito da fatturapa_v_1_2 produce una data senza timezone, se nell'xml della fattura la data è espressa con timezone (valida secondo specifica) python fallisce nel confronto delle due date (ho commentato il try per beccare l'errore effettivo):
```
  File "/home/sherpya/workspace/odoo/fatturapa/venv/local/lib/python2.7/site-packages/pyxb/binding/facets.py", line 660, in _validateConstraint_vx
    return (self.value() is None) or (self.value() <= value)
TypeError: can't compare offset-naive and offset-aware datetimes
```

purtroppo se in fatturapa_v_1_2 si inserisce la data con il timezone (es. 1970-01-01Z) si verifica il problema nel caso che nella fattura ci sia una data senza timezone

Ho provato a mettere le mani nel pyxb ma la cosa non sembra di facile soluzione, nel frattempo ho disabilitato il controllo sulla data minima, tra l'altra un 1970-01-01 inclusivo è un controllo poco furbo, perché se ho fatto un errore è molto probabile che mi ritrovi proprio quella data essendo ts = 0

# fixes

- [ ] v8: https://github.com/OCA/l10n-italy/pull/1012
- [x] v10: https://github.com/OCA/l10n-italy/pull/998
- [ ] v11:
- [x] v12: https://github.com/OCA/l10n-italy/pull/1050

**Comment by eLBati** [comment]
@sherpya potresti descrivere i passi per riprodurre il problema in odoo?

**Comment by sherpya** [comment]
prendi una fattura xml, su DatiGeneraliDocumento metti come data 2019-01-11+01:00
poi prova a farla entrare su odoo, per evitare tutta la trafila puoi prendere _ds.py e fatturapa_v_1_2.py
metterli in una directory, cambiare l'import di fatturapa in `import _ds as _ImportedBinding__ds`
e fare un file main:
```python
from fatturapa_v_1_2 import CreateFromDocument

if __name__ == '__main__':
    xmld = open('out.xml').read().decode('utf-8')
    xml = CreateFromDocument(xmld)
```

**Comment by sherpya** [comment]
fattura_v_1_2.py
commento:
```python
DataFatturaType._InitializeFacetMap(DataFatturaType._CF_minInclusive)
```

**Comment by eLBati** [comment]
@sherpya potresti proporre la PR?

**Comment by eLBati** [comment]
> vorrei sapere in ogni caso da chi ha fatto lo standard che senso ha una data (senza ora) con il timezone

Sì, questo sarebbe da chiedere :sweat_smile:

**Comment by sherpya** [comment]
> @sherpya potresti proporre la PR?

nella specifica della fattura PA il controllo c'è (anche se poco utile in effetti), al momento però non è di facile soluzione, bisognerebbe aprire un bug in pyxb, poi rigenerando il py rispunterebbe, secondo te è una buona idea?

**Comment by eLBati** [comment]
@sherpya io intendevo la modifica che hai fatto che ti permette di importare. Almeno da avere un workaround, eventualmente temporaneo.

**Comment by sherpya** [comment]
la modifica è disabilitare il controllo sulla data >= 1970-01-01, se vuoi ti faccio PR magari metto un FIXME dentro

**Comment by eLBati** [comment]
>
> la modifica è disabilitare il controllo sulla data >= 1970-01-01, se vuoi
> ti faccio PR magari metto un FIXME dentro
>
Sì grazie

**Comment by sherpya** [comment]
stavo guardando questa libreria https://pypi.org/project/xmlschema/, sembra funzionare senza problemi, solo il validate ritorna errori strani quando non valida

**Comment by sherpya** [comment]
come non detto lxml è capace di farlo ed è già nelle dipendenze di odoo

**Comment by sherpya** [comment]
purtroppo il codice è troppo basato su pyxb non sembra facile sostituire il tutto, nel frattempo ho segnalato il problema a pyxb che pare sia in abbandono comunque ;(

**Comment by eLBati** [comment]
Ah leggo ora https://github.com/pabigot/pyxb/issues/100

Allora a lungo termine vedo 2 strade:

1. Diventiamo maintainers di pyxb
2. Lo sostituiamo con qualcos'altro

**Comment by sherpya** [comment]
lxml andrebbe bene ma va cambiata un po' di roba, per la creazione non so se con lxml si può fare, per il bug della data, la modifica aggiungedo la __new__ è manutenibile

**Comment by eLBati** [comment]
La creazione dell'XML con `lxml` sicuramente si può fare. Sarebbe forse un po' più scomoda.

In effetti probabilmente conviene liberarsi di pyxb...

**Comment by eLBati** [comment]
@OCA/local-italy-developers in descrizione il link alla PR per la 10.
Da revisionare ed eventualmente portare alle altre versioni

**Comment by eLBati** [comment]
Un revisione per la 12 https://github.com/OCA/l10n-italy/pull/1050 ?

**Comment by sherpya** [comment]
> Un revisione per la 12 #1050 ?

dovrebbe essere praticamente identica a quella della 10 no? volendo poi si può anche pensare di portare #1218

**Comment by eLBati** [comment]
> dovrebbe essere praticamente identica a quella della 10 no?

Sì. Faccio merge?

> volendo poi si può anche pensare di portare #1218

Certo. Il porting alle varie versioni lo tracciamo qui https://github.com/OCA/l10n-italy/issues/1172

PS: hai già visto https://github.com/OCA/l10n-italy/wiki/Team-di-sviluppo ?

**Comment by sherpya** [comment]
> > dovrebbe essere praticamente identica a quella della 10 no?
> 
> Sì. Faccio merge?

Ho diffato è identica a parte la compatibiltà con py3, se travis è felice io direi di procedere

> 
> > volendo poi si può anche pensare di portare #1218
> 
> Certo. Il porting alle varie versioni lo tracciamo qui #1172
> 
> PS: hai già visto https://github.com/OCA/l10n-italy/wiki/Team-di-sviluppo ?

Avevo visto quei quadratini in effetti ma non sapevo dove stava la documentazione :)

**Comment by eLBati** [comment]
Attenzione che ci sarà da modificare anche il `setup.py`: https://github.com/OCA/l10n-italy/pull/1517
